FROM plugins/base:linux-amd64

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="Drone Jenkins" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

COPY .profile /root/.profile
COPY .ashrc /root/.ashrc
COPY release/linux/amd64/drone-jenkins /bin/
RUN apk update && apk add vim

ENTRYPOINT ["/bin/drone-jenkins"]